### PR TITLE
Fix for the issue #2

### PR DESCRIPTION
**Pull request by Vignesh-Durairaj**

### CODE REVIEW

**Comment by cardil** [comment]
Please sign your commit with GPG. https://help.github.com/en/articles/signing-commits

**Comment by Vignesh-Durairaj** [comment]
Thank you for introducing me to the 'Signed Commits' for GIT. I just created a GPG signature (RSA). Could you please help me on the possibility of verifying / signing an older commit (which was made, prior to the creation of a signature).

**Comment by cardil** [comment]
Just commit with amend flag. Then push with force flag. Ask Google: resign git commit

**Comment by Vignesh-Durairaj** [comment]
Thanks for helping me out again. I'd added the GPG signature to the commit. Kindly review the same.

**Comment by cardil** [comment]
Thx!

**Pull request merged**
